"""Bounded-memory MuPDF drawing extraction, shared by a page's consumers.

The callback emits fill/stroke separately. Merge adjacent equal paths exactly as
PyMuPDF 1.26.4's list collector does, retaining clipping, groups and record order.
The spool contains only records generated by this process, never external pickle.
"""

from contextlib import contextmanager
import pickle
import tempfile


class DrawingSpool:
    def __init__(self, page, directory=None):
        self.file = tempfile.NamedTemporaryFile(
            dir=directory, prefix="drawings-", suffix=".spool"
        )
        self.count = 0
        self.pending = None
        self.failure = None
        try:
            page.get_cdrawings(extended=True, callback=self._accept)
            if self.failure is not None:
                raise self.failure
            self._flush()
            self.file.flush()
        except BaseException:
            self.close()
            raise

    def _flush(self):
        if self.pending is not None:
            pickle.dump(self.pending, self.file, protocol=5)
            self.count += 1
            self.pending = None

    def _accept(self, record):
        # Exceptions must be re-raised after the C callback returns: some MuPDF
        # builds otherwise log and suppress a disk-full/write failure.
        if self.failure is not None:
            return True
        try:
            previous = self.pending
            if (
                record.get("type") == "s"
                and previous is not None
                and previous.get("type") == "f"
                and previous.get("items") == record.get("items")
            ):
                self.pending = {**record, **previous, "type": "fs"}
            else:
                self._flush()
                self.pending = record.copy()
            return True
        except BaseException as exc:
            self.failure = exc
            return True

    def __len__(self):
        return self.count

    def __iter__(self):
        # Separate cursors permit nested consumers without retaining all paths.
        position = 0
        for _ in range(self.count):
            self.file.seek(position)
            record = pickle.load(self.file)
            position = self.file.tell()
            yield record

    def close(self):
        self.file.close()


class CachedPage:
    def __init__(self, page, spool):
        self._page, self._spool = page, spool

    def __getattr__(self, name):
        return getattr(self._page, name)

    def get_cdrawings(self, extended=None, **kwargs):
        if extended is True and not kwargs:
            return self._spool
        return self._page.get_cdrawings(extended=extended, **kwargs)


class CachedDocument:
    def __init__(self, pdf, index, page):
        self._pdf, self._index, self._page = pdf, index, page

    def __getattr__(self, name):
        return getattr(self._pdf, name)

    def __getitem__(self, index):
        return self._page if index == self._index else self._pdf[index]


@contextmanager
def cached_document(pdf, index, directory=None):
    page = pdf[index]
    spool = DrawingSpool(page, directory)
    try:
        yield CachedDocument(pdf, index, CachedPage(page, spool))
    finally:
        spool.close()
